---
title: Safe
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
    featured-image: ''
    posts:
    - 
    - 
    - 
email: fair-exchange@protonmail.com
description: A Safe, Secure, Smart Solution for the CryptoCurrency Community
baseurl: ''
url: https://safecoin.org
author:
  name: Safe
  email: fair-exchange@protonmail.com
  uri: https://safecoin.org
  bio: 
  facebook: https://www.facebook.com/safecoins/
  twitter: safecoins
  linkedin: https://www.linkedin.com/company/safecoins/
  gplus: 
  youtube: https://www.youtube.com/watch?v=13W3wmOFrAc&feature=youtu.be
links:
  bitcointalk: https://bitcointalk.org/index.php?topic=2838370
  blog: http://blog.safecoin.org/
  facebook: https://www.facebook.com/safecoins/
  linkedin: https://www.linkedin.com/company/safecoins/
  forum: http://forum.safecoin.org/
  github: https://github.com/Fair-Exchange
  reddit: https://www.reddit.com/r/SafeCoins/
  discord: https://discord.gg/EkXGdw6
  slack: https://safecoins.slack.com
  telegram: https://t.me/joinchat/HCqlLxEEFR_SQPd9VjSpBw
  twitter: https://twitter.com/safecoins
  youtube: https://www.youtube.com/watch?v=13W3wmOFrAc&feature=youtu.be
  whitepaper: "/assets/Safe%20White%20Paper.pdf"
wallets:
  safewalletwin: https://github.com/Fair-Exchange/safewallet/releases/download/v0.013w64/Safewallet-win32-x64-v0.013.zip
  safewalletmac: https://github.com/Fair-Exchange/safewallet/releases/tag/v0.013mac64
  safewalletlin: https://github.com/Fair-Exchange/safewallet/releases/download/v0.013lin64/Safewallet-linux-x64-v0.013.tar.gz
  safecoinwin: https://github.com/Fair-Exchange/safecoin/releases/download/v0.1-Windows/SafeCoin.zip
  safecoinmac: https://github.com/Fair-Exchange/safecoin/releases/tag/v0.013mac64
  safecoinlin: https://github.com/Fair-Exchange/safecoin/releases/download/v0.1-Linux/safecoin.tar.gz
future: true
show_drafts: true
lsi: false
permalink: pretty
paginate: 6
paginate_path: "/blog/page:num/"
excerpt_separator: 
markdown: kramdown
cloudinary:
  cloud_name: dw4i3sw5c
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: "(min-width: 50rem) 50rem, 90vw"
gems:
- jekyll-feed
- jekyll-gist
- jekyll-paginate
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-sass-converter
- jekyll-multiple-languages-plugin
exclude:
- _dev
- bower.json
- ".env.json"
- Gemfile
- Gemfile.lock
- gulpfile.js
- LICENSE.md
- node_modules
- package.json
- README.md
- vendor
- old-homepage.html
languages:
- en
exclude_from_localizations:
- assets
